In [34]:
import sqlite3
import pandas as pd
con=sqlite3.connect(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\data\raw\ipl.db')

In [35]:
def q(sql):
    return pd.read_sql_query(sql,con)

In [36]:
def run_sql_file(path):
    with open(path, 'r') as f:
        script = f.read()
    con.executescript(script)
    con.commit()
    print('ran', path)

In [37]:
q("""SELECT * FROM matches""")

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,Kolkata Knight Riders,140.0,NaN,win,BB McCullum,1,6,1,6,46.0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,Sunrisers Hyderabad,35.0,NaN,win,Yuvraj Singh,2,1,1,2,15.0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,NaN,7.0,win,SPD Smith,4,3,4,4,36.0
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,NaN,10.0,win,CA Lynn,5,6,6,6,57.0
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,NaN,6.0,win,GJ Maxwell,494,4,494,494,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,2026,6,Delhi,2026-04-27,Indian Premier League,39.0,male,T20,T20,...,Royal Challengers Bangalore,NaN,9.0,win,JR Hazlewood,252,1,1,1,4664.0
1208,1529283,2026,6,New Chandigarh,2026-04-28,Indian Premier League,40.0,male,T20,T20,...,Rajasthan Royals,NaN,6.0,win,D Ferreira,494,134,134,134,11389.0
1209,1529284,2026,6,Mumbai,2026-04-29,Indian Premier League,41.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,6.0,win,H Klaasen,3,2,3,2,1740.0
1210,1529285,2026,6,Ahmedabad,2026-04-30,Indian Premier League,42.0,male,T20,T20,...,Gujarat Titans,NaN,4.0,win,JO Holder,1,615,615,615,4098.0
1211,1529286,2026,6,Jaipur,2026-05-01,Indian Premier League,43.0,male,T20,T20,...,Delhi Capitals,NaN,7.0,win,KL Rahul,134,252,134,252,1409.0

In [38]:
def run_sql_file(path):
    with open(path, 'r') as f:
        script = f.read()
    con.executescript(script)
    con.commit()
    print('ran',path)

In [39]:
run_sql_file(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\test.sql')

ran C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\test.sql

In [40]:
run_sql_file(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\01_nulls_and_blanks.sql')

ran C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\01_nulls_and_blanks.sql

In [41]:
q("""select count(*) as blank_before
from players 
where trim(field_pos) = '';""")

   blank_before
0           612

In [42]:
q("""select count(*) as null_after
from v_players_clean
where field_pos_clean is null;""")

   null_after
0         700

In [43]:
run_sql_file(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\02_merge_categories.sql')

ran C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\02_merge_categories.sql

In [44]:
q("""select distinct team_name
from teams
order by team_name;""")

                      team_name
0           Chennai Super Kings
1               Deccan Chargers
2                Delhi Capitals
3                 Gujarat Lions
4                Gujarat Titans
5          Kochi Tuskers Kerala
6         Kolkata Knight Riders
7          Lucknow Super Giants
8                Mumbai Indians
9                 Pune Warriors
10                 Punjab Kings
11             Rajasthan Royals
12       Rising Pune Supergiant
13      Rising Pune Supergiants
14  Royal Challengers Bangalore
15          Sunrisers Hyderabad

In [45]:
q("""select distinct team_name_clean
from v_teams_clean
order by team_name_clean;""")

                team_name_clean
0           Chennai Super Kings
1               Deccan Chargers
2                Delhi Capitals
3                 Gujarat Lions
4                Gujarat Titans
5          Kochi Tuskers Kerala
6         Kolkata Knight Riders
7          Lucknow Super Giants
8                Mumbai Indians
9                 Pune Warriors
10                 Punjab Kings
11             Rajasthan Royals
12       Rising Pune Supergiant
13  Royal Challengers Bangalore
14          Sunrisers Hyderabad

In [46]:
run_sql_file(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\03_venue_names.sql')

ran C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\03_venue_names.sql

In [47]:
q("""select venue,count(*) as matches
from matches
where venue in('Wankhede Stadium','Wankhede Stadium, Mumbai')
group by venue;""")

                      venue  matches
0          Wankhede Stadium       73
1  Wankhede Stadium, Mumbai       57

In [48]:
q("""select venue,count(*) as matches
from matches
group by venue
order by matches desc limit 10;""")

                                       venue  matches
0                               Eden Gardens       77
1                           Wankhede Stadium       73
2                      M Chinnaswamy Stadium       65
3                           Feroz Shah Kotla       60
4                   Wankhede Stadium, Mumbai       57
5  Rajiv Gandhi International Stadium, Uppal       49
6            MA Chidambaram Stadium, Chepauk       48
7                     Sawai Mansingh Stadium       47
8        Dubai International Cricket Stadium       46
9   MA Chidambaram Stadium, Chepauk, Chennai       38

In [49]:
run_sql_file(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\04_dedupe_venues.sql')

ran C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\04_dedupe_venues.sql

In [50]:
q(""" SELECT COUNT(*),venue,city
FROM venues
GROUP BY venue
ORDER BY COUNT(*) DESC
LIMIT 10;""")

   COUNT(*)                                              venue       city
0         2                            Sharjah Cricket Stadium        NaN
1         2  Maharaja Yadavindra Singh International Cricke...     Mohali
2         2                Dubai International Cricket Stadium        NaN
3         2                 Dr DY Patil Sports Academy, Mumbai     Mumbai
4         1                   Zayed Cricket Stadium, Abu Dhabi  Abu Dhabi
5         1                           Wankhede Stadium, Mumbai     Mumbai
6         1                                   Wankhede Stadium     Mumbai
7         1       Vidarbha Cricket Association Stadium, Jamtha     Nagpur
8         1                                    SuperSport Park  Centurion
9         1                         Subrata Roy Sahara Stadium       Pune

In [51]:
run_sql_file(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\05_city_fallback.sql')

ran C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\05_city_fallback.sql

In [52]:
q("""
SELECT sql
FROM sqlite_master
WHERE type = 'view'
AND name = 'v_city_clean';
""")

                                                 sql
0  CREATE VIEW v_city_clean AS\nSELECT m.match_id...

In [53]:
print(q("""
SELECT sql
FROM sqlite_master
WHERE type = 'view'
AND name = 'v_city_clean';
""").iloc[0, 0])

CREATE VIEW v_city_clean AS
SELECT m.match_id,
       COALESCE(v.city,
                m.city,
                'UNKNOWN') AS city_clean
FROM v_matches_venue m
JOIN v_venues_clean v
  ON v.venue = m.venue

In [54]:
print(q("""
SELECT sql
FROM sqlite_master
WHERE type = 'view'
    AND name = 'v_city_clean';
""").iloc[0, 0])

CREATE VIEW v_city_clean AS
SELECT m.match_id,
       COALESCE(v.city,
                m.city,
                'UNKNOWN') AS city_clean
FROM v_matches_venue m
JOIN v_venues_clean v
  ON v.venue = m.venue

In [55]:
run_sql_file(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\06_season_year.sql')

ran C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\06_season_year.sql

In [56]:
q("""SELECT distinct season,season_year
FROM v_season where season = '2020/21';""")

    season  season_year
0  2020/21         2020

In [57]:
run_sql_file(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\07_win_definition.sql')

ran C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\07_win_definition.sql

In [58]:
from pathlib import Path
import re

sql_path = Path(r"C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\08_matches_clean.sql")
sql_text = sql_path.read_text(encoding="utf-8")

for line_number, line in enumerate(sql_text.splitlines(), start=1):
    if re.search(r"\bq\b", line, re.IGNORECASE):
        print(f"{line_number}: {line}")

In [59]:
import ast
import pandas as pd
d = pd.read_sql('select * from deliveries where fielders_involved is not null ', con)
d['fielders'] = d['fielders_involved'].apply(ast.literal_eval)
d = d.explode('fielders')
d['fielders'].value_counts().head(5)

fielders
MS Dhoni          258
KD Karthik        228
RV Uthappa        169
AB de Villiers    148
V Kohli           142
Name: count, dtype: int64